### ISSUE TITLE
ConnectButton cannot be found in module

### ISSUE THREAD

**Issue by Jharmony** [project-kardeshev/ao-wallet-kit#25]
**Describe the bug**
After installing the ao-wallet-kit dependency and wrapping my app with it I noticed that the ConnectBotton could not be used in my Dapp. 

**To Reproduce**
To reproduce the issues make sure that you install ao-wallet-kit, then wrap you app with <AOWalletKit>, after in your App.tsx file try to import the ConnectButton (like so import { ConnectButton } from '@project-kardeshev/ao-wallet-kit'
)

1. import { ConnectButton } from '@project-kardeshev/ao-wallet-kit''
2. See error: `Module '"@project-kardeshev/ao-wallet-kit"' has no exported member 'ConnectButton'.ts(2305)
import ConnectButton`

**Expected behavior**
Once ConnectButton is imported it should be found in the module, used in your App.tsx file. 

**Screenshots**
![image](https://github.com/user-attachments/assets/18d15724-3320-4ebc-894e-a352d4c5bf6c)

**Environment (please complete the following information):**

- Environment: Node
- SDK Version 1.0.2
- Node Version: v22.6.0
- Browser Chrome

**Additional context**
You're welcome

**Comment by atticusofsparta** [comment]
addressed in https://github.com/project-kardeshev/ao-wallet-kit/pull/24
